tasks:
  - init: gradle build

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - esbenp.prettier-vscode
    - wesbos.theme-cobalt2
    - ms-ceintl.vscode-language-pack-ru