tasks:
  - init: gradle build

vscode:
  extensions:
    - MS-CEINTL.vscode-language-pack-ru@1.45.1:3BPmaymIp042N9IQup7YKg==
    - wesbos.theme-cobalt2@2.1.6:VWNPJwfSoLU7CBtR//auFA==
    - esbenp.prettier-vscode@4.6.0:3ul2z2dsx8yqcbS8VovpnQ==