/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // Set up scanner for both tasks
        Scanner in = new Scanner(System.in);
        System.out.println("Reverse the array using stack:");
        reverseConsole(in);
        System.out.println("Reverse even items:");
        oddEvenConsole(in);
        in.close(); // Close input
    }

    /**
     * Reverse the array
     * 
     * @param items array of items
     */
    public static int[] reverse(int[] items) {
        IStack stack = new ArrayStack(50);
        int[] result = new int[items.length];
        for (int i = 0; i < items.length; i++) {
            stack.push(items[i]);
        }
        for (int i = 0; i < items.length; i++) {
            result[i] = stack.pop();
        }
        return result;
    }

    public static void reverseConsole(Scanner in) {
        // Using Scanner for Getting Input from User
        IStack stack = new ArrayStack(50);
        int temp = in.nextInt();
        while (temp != 0) {
            stack.push(temp);
            temp = in.nextInt();
        }
        while (!stack.isEmpty()) {
            System.out.println(stack.pop());
        }

    }

    public static void oddEvenConsole(Scanner in) {
        // Using Scanner for Getting Input from User
        IStack stack = new ArrayStack(50);
        IStack queue = new ArrayQueue(50);

        int temp = in.nextInt();
        boolean odd = true;
        while (temp != 0) {
            if (odd)
                queue.push(temp);
            else
                stack.push(temp);
            odd = !odd;
            temp = in.nextInt();
        }

        System.out.println("Stack content:");
        while (!stack.isEmpty()) {
            System.out.print(stack.pop() + " ");
        }
        System.out.println("\nQueue content:");
        while (!queue.isEmpty()) {
            System.out.print(queue.pop() + " ");
        }
    }
}
