/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testReverse() {
        int[] testArray = { 1, 2, 3, 4, 5 };
        int[] reverseArray = { 5, 4, 3, 2, 1 };
        int[] result = App.reverse(testArray);
        assertArrayEquals("Array should be reversed", reverseArray, result);
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test
    public void testReverseOdd() {
        int[] testArray = { 1, 2, 3, 4, 5 };
        int[] reverseArray = { 1, 4, 3, 2, 5 };
        int[] result = App.reverseOdd(testArray);
        assertArrayEquals("Array should be reversed", reverseArray, result);
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
