/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testReverse() {
        App classUnderTest = new App();
        int[] testArray = { 1, 2, 3, 4, 5 };
        int[] reverseArray = { 5, 4, 3, 2, 1 };
        int[] result = App.reverse(testArray);
        assertArrayEquals("Array should be reversed", reverseArray, result);
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
}
